# Generated by Django 4.1.6 on 2023-02-15 14:44

from django.db import migrations, models
import reg_users.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_users', '0003_alter_profile_telegram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[reg_users.models.validated], verbose_name='Имя'),
        ),
    ]
